<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add new absence' => 'Új hiányzó hozzáadása',
    'Reason' => 'Hiányzás oka',
    'Send' => 'Elküld',
    'There are no absences' => 'Nincsenek hiányzók',
    'This kid was already set as absent before' => 'Ezt a gyereket már beállítottad korábban mint hiányzó',
    'You have to install \'evolun-kid\' to use this module.' => '',
    'Choose a kid' => 'Válassz egy gyereket',
];
