<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'More events' => 'További események',
    'Recent events' => 'Közelgő események',
    'Related events' => 'Kapcsolódó események',
    '{participates} going' => '{participates} résztvevő',
    'Your events' => 'Eseményeid',
    'Absences' => 'Hiányzások',
    'There are no absences' => 'Nincsenek hiányzások',
    '{absences} absences' => '{absences} hiányzás',
    'You don\'t have any event yet' => 'Még nincsenek eseményeid',
    'There are no upcoming events' => 'Nincsenek közelgő események',
];
