<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add to calendar' => 'Naptárhoz adás',
    'Are you sure? Every data belongs this event will be deleted!' => 'Biztos vagy benne? Minden adat törlődni fog, ami az eseményhez tartozik!',
    'Basic info' => 'Alapadatok',
    'Camp' => 'Tábor',
    'Cancel' => 'Mégse',
    'Category' => 'Kategória',
    'Choose later' => 'Még senki',
    'Comments' => 'Hozzászólások',
    'Create succesful' => 'Sikeres létrehozás',
    'Create unsuccesful' => 'Sikertelen létrehozás',
    'Created at' => 'Létrehozva',
    'Created by' => 'Létrehozta',
    'Delete' => 'Törlés',
    'Description' => 'Leírás',
    'End' => 'Időpont (vége)',
    'Error' => 'Hiba',
    'Events' => 'Események',
    'Hike' => 'Túra',
    'I will be there' => 'Ott leszek',
    'Meeting' => 'Megbeszélés',
    'Memo' => 'Beszámoló',
    'Absences' => 'Hiányzó gyerekek',
    'New event' => 'Új esemény',
    'No one yet' => 'Még senki',
    'Organizer' => 'Szervező',
    'Participates' => 'Résztvevők',
    'Party' => 'Találkozó',
    'Place' => 'Helyszín',
    'Save' => 'Mentés',
    'Something went wrong when tried to cancel the application' => 'Nem sikerült visszamondani a jelentkezésed',
    'Something went wrong with the application' => 'Nem sikerült a jelentkezésed',
    'Something went wrong with the application as an organizer' => 'Nem sikerült a jelentkezésed',
    'Start' => 'Időpont (kezdés)',
    'Study' => 'Foglalkozás',
    'Successfully applied as an organizer' => 'Sikeresen jelentkeztél, mint szervező',
    'Successfully canceled the event' => 'Sikeresen visszamondtad a jelentkezésed az eseményre',
    'Title' => 'Esemény neve',
    'Update' => 'Módosítás',
    'Update event: {title}' => 'Esemény szerkesztése: {title}',
    'Update succesful' => 'Sikeres módosítás',
    'Update unsuccesful' => 'A módosítás sikertelen volt',
    'Updated at' => 'Utoljára módosítva',
    'Updated by' => 'Utoljára módosította',
    'Whole event' => 'Végig',
    'You can\'t apply to this event, because it\'s over' => 'Nem tudsz jelentkezni erre az eseményre, mert már véget ért',
    'You can\'t cancel the application beacuse the event is over!' => 'Nem tudod visszamondani a jelentkezésed erre az eseményre, mert már véget ért!',
    'You successfully applied to this event' => 'Sikeresen jelentkeztél az eseményre',
    'apply' => 'jelentkezem',
    'cancel' => 'mégsem',
    'days' => 'nap',
    '{participates} going' => '{participates} résztvevő',
];
